# Generated by Django 4.2.4 on 2023-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('instituicao_empresa', models.CharField(max_length=200)),
                ('como_conheceu', models.CharField(choices=[('redes_sociais', 'Redes sociais'), ('email', 'Email'), ('colegas', 'Colegas de trabalho'), ('edicoes_anteriores', 'Edições anteriores'), ('outros', 'Outros')], max_length=50)),
            ],
        ),
    ]
