# Generated by Django 4.2.4 on 2023-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
